### ISSUE TITLE
Dump running script’s backtrace when CKB-VM encounters fatal error

### ISSUE THREAD

**Issue by XuJiandong** [nervosnetwork/ckb-standalone-debugger#16]
@mohanson

**Comment by mohanson** [comment]
I have updated the ckb-vm-pprof for ckb-debugger

https://github.com/nervosnetwork/ckb-vm-pprof/pull/10 

It should be noted that to print the call stack, we have to do the followings:

- Use ckb-debugger with --pprof
- Binary compiled with debug symbols
