### ISSUE TITLE
ckb-debugger: terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/ckb-standalone-debugger#39]
[polyjuice_validator_86Mcycles.tar.gz](https://github.com/nervosnetwork/godwoken-internal/files/7482373/polyjuice_validator_86Mcycles.tar.gz)

I used ckb-debugger to analysis the above tx:
```sh
./release/ckb-debugger \
  --cell-index 2 --cell-type input \
  ---script-group-type lock \
  --bin validator \
  --max-cycles 200000000000 \
  --tx-file cycles_86667011-0c2b45c5a99226a666ee98cbe6e9a95f0b391038d1f07608af45c89452c4df9d-offchain-cancel-tx.json \
  --pprof polyjuice_validator_86Mcycles.log
```

and it return this:
```log
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Run result: 1
Total cycles consumed: 73176486
Transfer cycles: 448404, running cycles: 72728082
```

Polyjuice validator bin：
[tx_and_bins.tar.gz](https://github.com/nervosnetwork/godwoken-internal/files/7486315/tx_and_bins.tar.gz)

tx:
[86Mtx.tar.gz](https://github.com/nervosnetwork/godwoken-internal/files/7525586/86Mtx.tar.gz)

_Originally posted in https://github.com/nervosnetwork/godwoken-internal/issues/346#issuecomment-961895509_

**Comment by XuJiandong** [comment]
Out of memory. Please check the memory usage.

**Comment by Flouse** [comment]
I used `-g` option instead of 'O0' to compile validator, this problem has gone.
thx.
